import { Category } from './types';

export const LEARNING_CATEGORIES: Category[] = [
  {
    title: 'Animals',
    emoji: '🐶',
    color: 'bg-yellow-300 hover:bg-yellow-400',
    hasAgeFilter: false,
    items: [
      { name: 'Dog', emoji: '🐶', sound: 'woof woof' },
      { name: 'Cat', emoji: '🐱', sound: 'meow' },
      { name: 'Cow', emoji: '🐮', sound: 'moo' },
      { name: 'Lion', emoji: '🦁', sound: 'roar' },
      { name: 'Elephant', emoji: '🐘', sound: 'pawoo' },
      { name: 'Monkey', emoji: '🐵', sound: 'ooh ooh aah aah' },
      { name: 'Pig', emoji: '🐷', sound: 'oink' },
      { name: 'Horse', emoji: '🐴', sound: 'neigh' },
      { name: 'Sheep', emoji: '🐑', sound: 'baa' },
      { name: 'Frog', emoji: '🐸', sound: 'ribbit' },
      { name: 'Duck', emoji: '🦆', sound: 'quack' },
      { name: 'Chicken', emoji: '🐔', sound: 'cluck' },
      { name: 'Bear', emoji: '🐻', sound: 'growl' },
      { name: 'Tiger', emoji: '🐯', sound: 'roar' },
      { name: 'Giraffe', emoji: '🦒', sound: 'hum' },
      { name: 'Zebra', emoji: '🦓', sound: 'chirp' },
      { name: 'Penguin', emoji: '🐧', sound: 'squawk' },
      { name: 'Fox', emoji: '🦊', sound: 'yip' },
    ],
  },
  {
    title: 'Fruits',
    emoji: '🍎',
    color: 'bg-red-400 hover:bg-red-500',
    hasAgeFilter: false,
    items: [
      { name: 'Apple', emoji: '🍎' },
      { name: 'Banana', emoji: '🍌' },
      { name: 'Orange', emoji: '🍊' },
      { name: 'Strawberry', emoji: '🍓' },
      { name: 'Grapes', emoji: '🍇' },
      { name: 'Watermelon', emoji: '🍉' },
      { name: 'Pineapple', emoji: '🍍' },
      { name: 'Mango', emoji: '🥭' },
      { name: 'Cherry', emoji: '🍒' },
      { name: 'Peach', emoji: '🍑' },
      { name: 'Pear', emoji: '🍐' },
      { name: 'Blueberry', emoji: '🫐' },
      { name: 'Kiwi', emoji: '🥝' },
      { name: 'Lemon', emoji: '🍋' },
      { name: 'Avocado', emoji: '🥑' },
      { name: 'Coconut', emoji: '🥥' },
      { name: 'Tomato', emoji: '🍅' },
      { name: 'Melon', emoji: '🍈' },
    ],
  },
  {
    title: 'Vegetables',
    emoji: '🥕',
    color: 'bg-green-400 hover:bg-green-500',
    hasAgeFilter: false,
    items: [
      { name: 'Carrot', emoji: '🥕' },
      { name: 'Broccoli', emoji: '🥦' },
      { name: 'Potato', emoji: '🥔' },
      { name: 'Corn', emoji: '🌽' },
      { name: 'Bell Pepper', emoji: '🫑' },
      { name: 'Cucumber', emoji: '🥒' },
      { name: 'Eggplant', emoji: '🍆' },
      { name: 'Onion', emoji: '🧅' },
      { name: 'Mushroom', emoji: '🍄' },
      { name: 'Garlic', emoji: '🧄' },
      { name: 'Lettuce', emoji: '🥬' },
      { name: 'Pumpkin', emoji: '🎃' },
      { name: 'Sweet Potato', emoji: '🍠' },
      { name: 'Chili Pepper', emoji: '🌶️' },
      { name: 'Peas', emoji: '🫛' },
      { name: 'Olive', emoji: '🫒' },
      { name: 'Cauliflower', emoji: '🥦' },
      { name: 'Spinach', emoji: '🥬' },
      { name: 'Zucchini', emoji: '🥒' },
      { name: 'Radish', emoji: '🫑' },
      { name: 'Cabbage', emoji: '🥬' },
      { name: 'Ginger', emoji: '🫚' },
    ],
  },
  {
    title: 'Vehicles',
    emoji: '🚗',
    color: 'bg-sky-400 hover:bg-sky-500',
    hasAgeFilter: true,
    items: [
      { name: 'Car', emoji: '🚗', ageGroup: '0-2', sound: 'vroom vroom' },
      { name: 'Bus', emoji: '🚌', ageGroup: '2-4', sound: 'beep beep' },
      { name: 'Train', emoji: '🚂', ageGroup: '2-4', sound: 'choo choo' },
      { name: 'Airplane', emoji: '✈️', ageGroup: '2-4', sound: 'whoosh' },
      { name: 'Boat', emoji: '⛵️', ageGroup: '2-4', sound: 'swish swish' },
      { name: 'Bicycle', emoji: '🚲', ageGroup: '2-4', sound: 'ring ring' },
    ],
  },
  {
    title: 'Alphabets',
    emoji: '🔤',
    color: 'bg-violet-400 hover:bg-violet-500',
    hasAgeFilter: false,
    items: Array.from({ length: 26 }, (_, i) => String.fromCharCode('A'.charCodeAt(0) + i))
      .map(letter => ({ name: letter, emoji: letter })),
  },
  {
    title: 'Numbers',
    emoji: '🔢',
    color: 'bg-lime-400 hover:bg-lime-500',
    hasAgeFilter: false,
    items: [
      { name: 'One', emoji: '1' },
      { name: 'Two', emoji: '2' },
      { name: 'Three', emoji: '3' },
      { name: 'Four', emoji: '4' },
      { name: 'Five', emoji: '5' },
      { name: 'Six', emoji: '6' },
      { name: 'Seven', emoji: '7' },
      { name: 'Eight', emoji: '8' },
      { name: 'Nine', emoji: '9' },
      { name: 'Ten', emoji: '10' },
    ],
  },
  {
    title: 'Colors',
    emoji: '🎨',
    color: 'bg-pink-400 hover:bg-pink-500',
    hasAgeFilter: false,
    items: [
      { name: 'Red', emoji: '🔴' },
      { name: 'Blue', emoji: '🔵' },
      { name: 'Green', emoji: '🟢' },
      { name: 'Yellow', emoji: '🟡' },
      { name: 'Orange', emoji: '🟠' },
      { name: 'Purple', emoji: '🟣' },
      { name: 'Black', emoji: '⚫️' },
      { name: 'White', emoji: '⚪️' },
      { name: 'Brown', emoji: '🟤' },
    ],
  },
  {
    title: 'Shapes',
    emoji: '⭐',
    color: 'bg-teal-400 hover:bg-teal-500',
    hasAgeFilter: false,
    items: [
      { name: 'Circle', emoji: '🔵' },
      { name: 'Square', emoji: '🟪' },
      { name: 'Triangle', emoji: '🔺' },
      { name: 'Star', emoji: '⭐' },
      { name: 'Heart', emoji: '❤️' },
      { name: 'Rectangle', emoji: '🟩' },
    ],
  },
  {
    title: 'Body Parts',
    emoji: '👃',
    color: 'bg-orange-400 hover:bg-orange-500',
    hasAgeFilter: false,
    items: [
      { name: 'Eyes', emoji: '👀' },
      { name: 'Nose', emoji: '👃' },
      { name: 'Mouth', emoji: '👄' },
      { name: 'Ears', emoji: '👂' },
      { name: 'Hands', emoji: '👋' },
      { name: 'Feet', emoji: '🦶' },
      { name: 'Arms', emoji: '💪' },
      { name: 'Legs', emoji: '🦵' },
      { name: 'Fingers', emoji: '🖐️' },
      { name: 'Toes', emoji: '🦶' },
      { name: 'Teeth', emoji: '🦷' },
      { name: 'Tongue', emoji: '👅' },
      { name: 'Hair', emoji: '👱‍♀️' },
      { name: 'Knees', emoji: '🦵' },
    ],
  },
];